### ISSUE TITLE
Smartspacer crashing when LSPosed is Installed

### ISSUE THREAD

**Issue by Reiux** [KieronQuinn/Smartspacer#163]
### Description

Just as the title says, The app crashes if my LSPosed is Installed but if  I disable it, The app would open as usual. 

Then I try to change the package name of the app using Revanced while LSPosed still turned on and the app opens. 

But the only problem is that shizuku and disable battery optimization is not working since of course changing package name of an app can cause issues. So idk if this can be fix or not so yeah.

**Comment by KieronQuinn** [comment]
Post a log please, this isn't being sent to Crashlytics.

**Comment by Reiux** [comment]
Here's the crash log

`time: 1708009344635
msg: java.lang.SecurityException: Unknown calling package name 'com.kieronquinn.app.smartspacer'.
stacktrace: java.lang.SecurityException: Unknown calling package name 'com.kieronquinn.app.smartspacer'.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at com.google.android.gms.common.internal.zzac.getService(com.google.android.gms:play-services-basement@@18.1.0:9)
	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(com.google.android.gms:play-services-basement@@18.1.0:14)
	at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(com.google.android.gms:play-services-basement@@18.1.0:2)
	at com.google.android.gms.common.internal.zzg.zzd(com.google.android.gms:play-services-basement@@18.1.0:1)
	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.1.0:4)
	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.1.0:3)
	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.1.0:31)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8282)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
`

**Comment by KieronQuinn** [comment]
That's out of my hands unfortunately as it's a crash coming from Play Services. Given it's saying the calling package wasn't found, then yes it's likely caused by changing the package name.
