### ISSUE TITLE
[Bug] Lack of exception checks when launching intents in Client SDK

### ISSUE THREAD

**Issue by zobnin** [KieronQuinn/Smartspacer#203]
### Description

Hello. I'm using Client SDK for launchers and I've encountered a crash. It appears that there is a lack of proper exception checking when launching an intent:

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.android.calendar/time/1714922516087 flg=0x10208000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1023)
       at android.app.ContextImpl.startActivity(ContextImpl.java:994)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:403)
       at com.kieronquinn.app.smartspacer.sdk.client.views.templates.SmartspacerWeatherTemplatePageView.launchCalendar(SmartspacerWeatherTemplatePageView.kt:62)
       at com.kieronquinn.app.smartspacer.sdk.client.views.templates.SmartspacerWeatherTemplatePageView.setTarget$lambda$2$lambda$0(SmartspacerWeatherTemplatePageView.kt:44)
       at android.view.View.performClick(View.java:7455)
       at android.view.View.performClickInternal(View.java:7428)
       at android.view.View.access$3600(View.java:813)
       at android.view.View$PerformClick.run(View.java:28495)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7700)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Comment by KieronQuinn** [comment]
This is now absorbed in 1.0.10 of the client SDK. If the device doesn't have a calendar installed that can handle that intent there's nothing to do anyway, so it just does nothing.
