### ISSUE TITLE
[Bug] App crashed in background

### ISSUE THREAD

**Issue by NikunjKhangwal** [KieronQuinn/Smartspacer#207]
### Description

The app randomly crashed in background while i was watching YouTube.

Here's the Logs:

`FATAL EXCEPTION: Binder:19073_5
Process: com.kieronquinn.app.smartspacer, PID: 19073
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 2173912 free bytes and 2122KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
	at android.os.Binder.execTransact(Binder.java:1147)`

`FATAL EXCEPTION: Crashlytics Exception Handler1
Process: com.kieronquinn.app.smartspacer, PID: 19073
java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 1688760 free bytes and 1649KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.Arrays.copyOf(Arrays.java:3578)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:177)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:543)
	at java.lang.StringBuilder.append(StringBuilder.java:186)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateFrameData(CrashlyticsReportDataCapture.java:430)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateFramesList(CrashlyticsReportDataCapture.java:375)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateThreadData(CrashlyticsReportDataCapture.java:366)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateThreadData(CrashlyticsReportDataCapture.java:358)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateThreadsList(CrashlyticsReportDataCapture.java:348)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateExecutionData(CrashlyticsReportDataCapture.java:313)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateEventApplicationData(CrashlyticsReportDataCapture.java:260)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.captureEventData(CrashlyticsReportDataCapture.java:112)
	at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistEvent(SessionReportingCoordinator.java:330)
	at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistFatalEvent(SessionReportingCoordinator.java:131)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:214)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:199)
	at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:105)
	at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:67)
	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
	at java.lang.Thread.run(Thread.java:1012)`

**Comment by KieronQuinn** [comment]
Should be fixed in 1.7.4
