### ISSUE TITLE
[Bug] Force close on Android 15

### ISSUE THREAD

**Issue by HankAviator** [KieronQuinn/Smartspacer#270]
### Description

Hello,

I can't provide additional log except for logcat, as the app crashes immediately after I open it.

I am using HyperOS 2 based on Android 15, Xiaomi 14.

```
2024-12-03 12:29:59.157 13282 13282 com.kieronquinn.app.smartspacer E AndroidRuntime : FATAL EXCEPTION: main
Process: com.kieronquinn.app.smartspacer, PID: 13282
java.lang.RuntimeException: Unable to instantiate application com.kieronquinn.app.smartspacer.Smartspacer package com.kieronquinn.app.smartspacer: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.kieronquinn.app.smartspacer.repositories.AlarmRepository']'
	at android.app.LoadedApk.makeApplicationInner(Unknown Source:347)
	at android.app.LoadedApk.makeApplicationInner(Unknown Source:1)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:1026)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:1157)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loopOnce(Unknown Source:194)
	at android.os.Looper.loop(Unknown Source:34)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:9)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:392)
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.kieronquinn.app.smartspacer.repositories.AlarmRepository']'
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
	at org.koin.core.registry.InstanceRegistry.createEagerInstances(InstanceRegistry.kt:91)
	at org.koin.core.registry.InstanceRegistry.createAllEagerInstances$koin_core(InstanceRegistry.kt:62)
	at org.koin.core.Koin.createEagerInstances(Koin.kt:330)
	at org.koin.core.KoinApplication.createEagerInstances(KoinApplication.kt:74)
	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:65)
	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:40)
	at com.kieronquinn.app.smartspacer.Smartspacer.attachBaseContext(Smartspacer.kt:536)
	at android.app.Application.attach(Unknown Source:0)
	at android.app.Instrumentation.newApplication(Unknown Source:12)
	at android.app.LoadedApk.makeApplicationInner(Unknown Source:188)
	... 11 more
Caused by: java.lang.RuntimeException: Cannot read value from namespace systemui from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.
	at android.app.FeatureFlagsImpl.load_overrides_systemui(Unknown Source:180)
	at android.app.FeatureFlagsImpl.sortSectionByTime(Unknown Source:4)
	at android.app.Flags.sortSectionByTime(Unknown Source:2)
	at android.app.Notification.<init>(Unknown Source:45)
	at androidx.core.app.NotificationCompat$Builder.<init>(NotificationCompat.java:1065)
	at com.kieronquinn.app.smartspacer.components.notifications.NotificationsKt.createNotification(Notifications.kt:26)
	at com.kieronquinn.app.smartspacer.repositories.NotificationRepositoryImpl.showNotification(NotificationRepository.kt:220)
	at com.kieronquinn.app.smartspacer.repositories.AlarmRepositoryImpl.showBatteryOptimisationNotification(AlarmRepository.kt:386)
	at com.kieronquinn.app.smartspacer.repositories.AlarmRepositoryImpl.enqueueDailyUpdateReceiver(AlarmRepository.kt:307)
	at com.kieronquinn.app.smartspacer.repositories.AlarmRepositoryImpl.<init>(AlarmRepository.kt:414)
	at com.kieronquinn.app.smartspacer.repositories.AlarmRepositoryImpl.<init>(AlarmRepository.kt:105)
	at com.kieronquinn.app.smartspacer.Smartspacer$singles$1$15.invoke(Smartspacer.kt:358)

2024-12-03 12:29:59.157 13282 13282 com.kieronquinn.app.smartspacer E AndroidRuntime : at com.kieronquinn.app.smartspacer.Smartspacer$singles$1$15.invoke(Smartspacer.kt:358)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
	... 26 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.app.Application.getContentResolver()' on a null object reference
	at android.provider.Settings$Config.getContentResolver(Unknown Source:4)
	at android.provider.Settings$Config.getStrings(Unknown Source:0)
	at android.provider.SettingsConfigDataStore.getProperties(SettingsConfigDataStore.java:48)
	at android.provider.DeviceConfig.getPropertiesWithoutOverrides(DeviceConfig.java:1125)
	at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1115)
	at android.app.FeatureFlagsImpl.load_overrides_systemui(Unknown Source:6)
	... 39 more
```

**Comment by KieronQuinn** [comment]
#263
